name: docker builds
on:
  push:
    paths:
    - 'Dockerfile*'
    - '.github/**'
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 */8 * * *'
  watch:
    types: [started]

jobs:
  build-n-push:
    name: Build and push docker images
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Login to Docker Registry
      run: docker login ${DOCKER_REGISTRY} --username ${DOCKER_USERNAME} --password ${DOCKER_PASSWORD}
      env:
        DOCKER_REGISTRY: docker.io
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    - name: build-n-push
      env:
        DOCKER_REGISTRY: docker.io
        DOCKER_IMAGE_NAME: rcmorano/ubuntu-crond:latest
      run: |
        docker build -t ${DOCKER_IMAGE_NAME} .
        docker push ${DOCKER_IMAGE_NAME}
